import { createElement } from 'lwc';
import PaginationDemo3 from 'c/paginationDemo3';
import getAccounts from'@salesforce/apex/AccountController.getAccountList';


const mockGetAccountList = require('./data/getAccountRecords.json');

// jest.mock(moduleName,factory,options)
jest.mock(
    '@salesforce/apex/AccountController.getAccountList',
    () => {
      return {
        default:jest.fn()
      };
    },
    { virtual: true }
  );

describe('c-pagination-demo3', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
        // Prevent data saved on mocks from leaking between tests
             jest.clearAllMocks();
    })

    beforeEach(() => {
        const element = createElement('c-pagination-demo3', {
                is: PaginationDemo3
        })
                document.body.appendChild(element);
    })
    
    // eslint-disable-next-line jest/expect-expect
    it('render accounts returned from imperative apex call' ,()=>{
        getAccounts.mockResolvedValue(mockGetAccountList);
        // eslint-disable-next-line @lwc/lwc/no-document-query
        const element = document.querySelector('c-pagination-demo3')
        // eslint-disable-next-line no-unused-vars
        const tableElement = element.shadowRoot.querySelector('table');

        return new Promise(setImmediate).then(() => {
            // eslint-disable-next-line no-unused-vars
            const accDetails = element.shadowRoot.querySelectorAll('tbody');
            expect(accDetails.length).toBe(mockGetAccountList.length);
            //expect(accDetails[0].textContent).toBe(mockGetAccountList[0].Id , mockGetAccountList[0].Name ,mockGetAccountList[0].Phone);

        })

    })
    
});






    // describe('getAccounts  data', () => {
    //     it('renders four records', () => {
    //       const element = createElement('c-pagination-demo3', {
    //         is: PaginationDemo3
    //       });
    //       document.body.appendChild(element);
            
    //       // Emit data from getAccounts
    //       getAccounts.emit(mockGetAccountList);
            
    //       return Promise.resolve().then(() => {
    //         // Select elements for validation
    //         const accountElements = element.shadowRoot.querySelectorAll('table');
    //         expect(accountElements.length).toBe(mockGetAccountList.length);
    //         expect(accountElements[0].textContent).toBe(mockGetAccountList[0].Id , mockGetAccountList[0].Name ,mockGetAccountList[0].Phone);
    //       });
    //     });

       
// });







//================================================================================================================c/childComp1

// import { createElement } from 'lwc';
// import PaginationDemo3 from 'c/paginationDemo3';

// describe('c-pagination-demo3', () => {
//     afterEach(() => {
//         // The jsdom instance is shared across test cases in a single file so reset the DOM
//         while (document.body.firstChild) {
//             document.body.removeChild(document.body.firstChild);
//         }
//         // Prevent data saved on mocks from leaking between tests
//     });
    

//         it('TODO: test case generated by CLI command, please fill in test logic', () => {
//             // Arrange
//             const element = createElement('c-pagination-demo3', {
//                 is: PaginationDemo3
//             });

//             // Act
//             document.body.appendChild(element);

//             // Assert
//             // const div = element.shadowRoot.querySelector('div');
//             expect(1).toBe(1);
//         });
//     });
